Homework 3
Brevid1994/React-tasks pull request #2
Opened 2021-03-01 19:18 UTC by Brevid1994

@NearFutureBand подгрузил на проверку пока что только самостоялку с лекции

2021-03-06 05:32 UTC, NearFutureBand requested changes
В целом все хорошо, по задаче с дропдауном есть пара моментов. Домашку про условный рендеринг и вывод компонентов циклом засчитываю. В практическом - нужно пофиксить третью задачу про дропдаун

2021-03-06 05:32 UTC, NearFutureBand commented on lern-react/src/Components/ClassWork3/BurgerMenu.js
> +              return <li> { ingridients }
Нету пропа key. Надо как-то организовать - можешь воспользоваться подходом, который есть на одной из записи занятий с разбором задач практики.

2021-03-06 05:32 UTC, NearFutureBand commented on lern-react/src/Components/ClassWork3/BurgerMenu.js
> +                  { this.state.quantity }
Каждый элемент списка содержит по две кнопки и числу. И каждая кнопка изменяет одно значение - this.state.quanity. И это число выводится здесь. Получается что прибавляя один ингредиент - прибавляются все. В условии задачи подразумевается что quantity - это сумма всех выбранных ингредиентов. Решить эту задачу можно создав отдельный компонент с кнопками + и - и со своим стейтом. И этот компонент добавить к каждому элементу списка здесь. А вот как после всего этого изменять quantity подскажет задача из трелло https://trello.com/c/X5iRe4ih. Но лучше перед этим пофиксить все остальные баги

2021-03-06 05:32 UTC, NearFutureBand commented on lern-react/src/Components/ClassWork3/BurgerMenu.js
> +          <div onClick = { this.startLoading } >Close ^
Тут событие клика привязано к диву, в котором также находится весь список. И кликая на любой плюс или минус у элементов списка весь дропдаун закрывается и список пропадает. Кнопку с онкликом просто вынеси отдельно, и список выводи в зависимости от условия.

2021-03-06 05:32 UTC, NearFutureBand commented on lern-react/src/Components/Homework3/Users.js
> +                    return <div className='block-for-user' key = {item.id}>
Название свойства для ключа там вроде бы называется item._id - проверь, пожалуйста. Плюс можно в консоли посмотреть ругается ли реакт на key или нет. Когда добавляешь key - всегда глянь в консоль, точно ли ошибки там нет

2021-03-13 08:51 UTC, Brevid1994 commented
исправил все, кроме добавление/удаления ингр., создать новый отдельный компонент необходимо внутри класса? или создать другой класс, и через пропы сделать функцию?

2021-03-17 15:42 UTC, merged